config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    def index
        @flats = Flat.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
<h1 class="text-center my-4">All our Flats (<%= @flats.count %>)</h1>
<div class="row">
<div class="d-flex justify-content-around align-items-end card shadow rounded ">
<% @flats.each do |flat| %>
<div class="col-sm">
    <li class="border mx-3 p-2 text-decoration-none align-items-end">
      <%= flat.description %><br><br>
      <%= flat.address %><br><br>
      <div class="small">
         <i class="material-icons">people</i><%= flat.number_of_guests %>
         <i class="material-icons">euro_symbol</i><%= flat.price_per_night %>
      </div>
    </li>
    </div>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
  <h3><%= link_to "Simple Airbnb", flats_path %></h3>
  <h4><%= link_to "Add Flat", new_flat_path %></h4>
  </nav>
    <%= yield %>
  </body>
</html>